# Generated by Django 6.0.7 on 2026-07-15 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smclone", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
