# Generated by Django 6.0.7 on 2026-07-15 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smclone", "0002_alter_profile_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="privacy_settings",
            field=models.BooleanField(default=False),
        ),
    ]
