# Generated by Django 6.0.7 on 2026-07-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smclone", "0005_usernamerecoverycode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, upload_to="photos/post"),
        ),
    ]
