# Generated by Django 6.0.7 on 2026-07-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smclone", "0006_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
