# Generated by Django 6.0.6 on 2026-07-03 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_todo_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="user",
        ),
    ]
